kind: Service
apiVersion: v1
metadata:
  name: stocks
  namespace: apps
  labels:
    app: stocks
    service: stocks
spec:
  selector:
    app: stocks
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-8080
      port: 8080
      targetPort: 8080
    - port: 80
      name: http-80
      protocol: TCP
      targetPort: 8080