apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yml
  - cluster-role.yml
  - cluster-role-binding.yml
  - service.yml
  - service-monitor.yml
  - grafana/grafana-volume.yml
  - grafana/grafana-datasource.yml
  - grafana/grafana-secret.yml
  - grafana/grafana.yml
namespace: monitoring