apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    prometheus: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector: { }
  serviceMonitorNamespaceSelector: { }
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true