apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks
  namespace: apps
  labels:
    app: stocks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks
  template:
    metadata:
      labels:
        app: stocks
    spec:
      containers:
        - name: stocks
          image: eltonmmoreira/stocks:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: stocks-config
          livenessProbe:
            httpGet:
              path: /stocks/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /stocks/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "600Mi"
              cpu: "200m"