apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: wallet-app
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wallet
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 500Mi