apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  namespace: apps
  labels:
    app: wallet
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet
      version: v1
  template:
    metadata:
      labels:
        app: wallet
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: wallet
          image: eltonmmoreira/wallet:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: wallet-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "600Mi"
              cpu: "200m"