apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wallet
  namespace: apps
  labels:
    app: wallet
spec:
  selector:
    matchLabels:
      app: wallet
  endpoints:
    - port: http-8080
      path: /actuator/prometheus
      interval: 10s