kind: Service
apiVersion: v1
metadata:
  name: wallet
  namespace: apps
  labels:
    app: wallet
    service: wallet
spec:
  selector:
    app: wallet
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-8080
      port: 8080
      targetPort: 8080
    - port: 80
      name: http-80
      protocol: TCP
      targetPort: 8080