apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-redis
  namespace: apps
  labels:
    app: stocks-redis
spec:
  selector:
    matchLabels:
      app: stocks-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: stocks-redis
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: master
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379