apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: apps
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: tcp-6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis