apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  ports:
    - name: http-9090
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    app: prometheus