apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: public
spec:
  rules:
    - http:
        paths:
          - path: /stocks(/|$)(.*)
            pathType: Prefix
#            Exact
            backend:
              service:
                name: stocks
                port:
                  number: 80