apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: stocks
resources:
  - namespace.yml
  - stocks/app/configmap.yml
  - stocks/app/configmap-v2.yml
  - stocks/app/deployment.yml
  - stocks/app/autoscaling.yml
  - stocks/app/deployment-v2.yml
  - stocks/app/service.yml
  - stocks/app/service-monitor.yml
  - stocks/redis/deployment.yml
  - stocks/redis/service.yml
  - stocks/traffic-splitting/destination-rule.yml
  - stocks/traffic-splitting/virtual-service.yml
  - gateway.yml
namespace: apps